# Generated by Django 5.2.4 on 2025-07-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('member', 'メンバー'), ('senior_member', 'シニアメンバー'), ('team_lead', 'チームリード'), ('project_manager', 'プロジェクトマネージャー'), ('admin', '管理者'), ('super_admin', 'スーパー管理者')], default='member', max_length=20, verbose_name='役職'),
        ),
    ]
