# Generated by Django 5.2.4 on 2025-07-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('member', 'メンバー'), ('admin', '管理者'), ('owner', 'オーナー')], default='member', max_length=20, verbose_name='役職'),
        ),
    ]
